# Dependencies
markdown:         redcarpet
highlighter: pygments

# Permalinks
permalink:        pretty

# Setup
title:            The Daily Awesome Blog
tagline:          'Thoughts, stories and ideas.'
description:      ''
url:              http://bigappleinsider.github.io/

author:
  name:           'Vlad Vinnikov'
  url:            https://twitter.com/vinnikau

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/bigappleinsider/bigappleinsider.github.io
#  repo:           https://github.com/bigappleinsider/bigappleinsider.github.io
